/* prompt generator */
var prompts = [

"What is one thing that you take for granted that you are grateful for today?",
"How has expressing gratitude impacted your life and the people around you?",
"What are three things that you are grateful for in your current season of life?",
"When was the last time you expressed gratitude to someone who has positively impacted your life?",
"How has a difficult experience in your life helped you to appreciate something you may have taken for granted?",
"What are some challenges or obstacles that you've faced in the past that you are now grateful for?",
"Who is someone in your life that you are grateful for, but may not have expressed it to them yet?",
"What is something that you've accomplished recently that you are grateful for?",
"How has your perception of gratitude changed over time?",
"What are some small things that you are grateful for that you may overlook in your day-to-day life?",
"How has gratitude helped you to cope with difficult situations in your life?",
"What are some ways you can incorporate gratitude into your daily routine?",
"What is something that you are grateful for that you may have once taken for granted, but now see in a new light?",
"How can you express gratitude to those who may not receive it often, such as service workers or strangers?",
"How has your attitude towards gratitude affected your overall happiness and well-being?",
"What are some ways you can show gratitude towards yourself for the things you've accomplished?",
"How has expressing gratitude helped you to develop stronger relationships with the people around you?",
"What are some unexpected things in your life that you are grateful for?",
"How has gratitude helped you to stay positive during challenging times?",
"What are some things you can do to show gratitude for the natural world around you?",
"How has expressing gratitude helped you to overcome negative thoughts or emotions?",
"What is something that you are grateful for that you may have never thought about before?",
"How has gratitude helped you to become a better person or make positive changes in your life?",
"What are some ways you can incorporate gratitude into your interactions with others?",
"How has gratitude helped you to find joy in the small moments of your life?",
"What are some ways you can practice gratitude during difficult times?",
"How has gratitude helped you to become more resilient in the face of challenges?",
"What are some ways you can express gratitude towards those who may have hurt or challenged you in the past?",
"How has expressing gratitude helped you to develop a more positive outlook on life?",
"What are some ways you can show gratitude towards the people who have supported you throughout your life?",
"What are your top three goals for the next year, and how do you plan to achieve them?",
"How have your past successes and failures influenced your current goals?",
"What is one goal that you've been putting off, and why?",
"How do your current goals align with your values and beliefs?",
"What are some ways you can break down a big goal into smaller, more manageable steps?",
"How have the goals you've set in the past helped you to grow and develop as a person?",
"What is one goal that you've achieved that you're particularly proud of, and why?",
"How have the people around you influenced your goals and aspirations?",
"What are some potential obstacles that could get in the way of achieving your goals, and how can you overcome them?",
"How do your goals contribute to your overall sense of purpose and fulfillment?",
"What is one goal that you've set for yourself that you know will be challenging, but worthwhile?",
"How has your mindset towards goals changed over time?",
"What are some ways you can hold yourself accountable for achieving your goals?",
"How have the goals you've set for yourself impacted your personal and professional life?",
"What is one goal that you've set for yourself that aligns with a greater cause or purpose?",
"How have you learned from setbacks or failures when pursuing your goals in the past?",
"What is one goal that you've achieved that has surprised you the most, and why?",
"What are some ways you can celebrate your successes when you achieve your goals?",
"How do your current goals contribute to your long-term vision for your life?",
"What is one goal that you've set for yourself that requires you to step outside of your comfort zone?",
"How do your goals reflect your priorities and what matters most to you in life?",
"What are some ways you can adjust your goals as your circumstances and priorities change?",
"How has pursuing your goals helped you to develop resilience and perseverance?",
"What is one goal that you've set for yourself that requires collaboration or working with others?",
"How do you balance setting challenging goals with being realistic and attainable?",
"What are some ways you can overcome fear or self-doubt when pursuing your goals?",
"How has setting and achieving goals helped you to develop a sense of purpose and direction in your life?",
"What is one goal that you've set for yourself that has required you to learn something new, and how did you approach that learning process?",
"How do your goals contribute to your personal growth and development?",
"What is one goal that you've set for yourself that aligns with a greater sense of purpose or calling?",
"What are the core values that guide your life, and how have they evolved over time?",
"What are some patterns or habits that you've noticed about yourself, and how do they impact your life?",
"How have your past experiences and challenges shaped the person you are today?",
"What is one thing you wish you had done differently in the past, and what have you learned from that experience?",
"How do you approach difficult conversations or situations, and what could you do differently to improve those interactions?",
"What is one area of your life that you've been neglecting, and why?",
"How do you handle failure or setbacks, and what have those experiences taught you about yourself?",
"What are some limiting beliefs you hold about yourself, and how have they held you back from reaching your full potential?",
"How has your relationship with yourself changed over time, and what do you want to cultivate moving forward?",
"What are some areas of your life where you could benefit from setting healthier boundaries?",
"How do you balance self-care with achieving your goals and responsibilities?",
"What are some ways you can improve your communication skills, both with yourself and with others?",
"What are some things that you've been avoiding, and what is holding you back from confronting those things?",
"How do you approach decision-making, and what factors do you consider when making important choices?",
"What is one area of your life where you could benefit from seeking outside support or guidance?",
"How has your sense of identity evolved over time, and what factors have influenced that evolution?",
"What are some ways you can cultivate more self-compassion and forgiveness in your life?",
"How have your relationships with others influenced your relationship with yourself?",
"What are some steps you can take to improve your physical, emotional, or mental health?",
"How have your experiences with success and achievement shaped your self-image?",
"What is one area of your life where you tend to experience self-doubt or insecurity, and how can you address those feelings?",
"How do you prioritize your values and goals when making decisions or taking action?",
"What are some ways you can develop a more positive and empowering self-talk?",
"How have your experiences with failure or disappointment influenced your approach to taking risks?",
"What is one thing you've learned about yourself through a challenging or transformative experience?",
"How do you approach change, and what strategies do you use to adapt to new circumstances?",
"What are some ways you can develop greater emotional intelligence and empathy towards yourself and others?",
"How has your relationship with your body evolved over time, and what steps can you take to cultivate greater self-acceptance?",
"What are some ways you can create more balance and fulfillment in your life?",
"How do you define success and fulfillment for yourself, and how do you align your actions with those values?",
"What would happen if you woke up one day with the ability to read minds?",
"Can you write a story that takes place entirely in one room?",
"What would the world be like if technology suddenly ceased to exist?",
"Can you write a story that includes a character who is invisible to everyone else?",
"What if the main character of your story had the power to control time?",
"What would happen if your character suddenly found themselves transported to a different time period?",
"Can you write a story that takes place entirely through letters or emails between two characters?",
"What if your character woke up one day with no memory of their past?",
"Can you write a story that incorporates elements of magic or the supernatural?",
"What if your character discovered a hidden world that existed right alongside our own?",
"Can you write a story that includes a character who can talk to animals?",
"What if the world was ruled by a single corporation or government?",
"Can you write a story that takes place in a future where space travel is commonplace?",
"What if your character was the last person on Earth?",
"Can you write a story that is told from the perspective of a non-human character, like an animal or a plant?",
"What if your character found themselves stuck in a time loop, reliving the same day over and over?",
"Can you write a story that takes place in a post-apocalyptic world?",
"What if your character discovered a secret society that had been hiding in plain sight?",
"Can you write a story that explores themes of identity or self-discovery?",
"What if your character was granted three wishes by a genie?",
"Can you write a story that takes place on a deserted island?",
"What if your character had the power to control the weather?",
"Can you write a story that includes a character who is immortal?",
"What if your character discovered a mysterious book that held the key to unlocking a hidden power or knowledge?",
"Can you write a story that takes place in a world where everyone has a unique superpower?",
"What if your character was forced to make a difficult moral choice that would have far-reaching consequences?",
"Can you write a story that explores the relationship between humans and artificial intelligence?",
"What if your character discovered a portal to another dimension?",
"Can you write a story that is told from the perspective of an inanimate object?",
"What if your character found themselves trapped in a dream world, unable to wake up?",
"What are some limiting beliefs that you've held onto for too long? How have they held you back?",
"What is something that you've always wanted to try but have been too afraid to attempt? Why?",
"In what ways have you grown in the past year? What have you learned about yourself?",
"What is something that you've been procrastinating on that would bring you closer to your goals? Why have you been putting it off?",
"What is a habit that you would like to break or start? Why is it important to you?",
"What are some things that you've accomplished that you are proud of? Why are they meaningful to you?",
"In what ways do you tend to self-sabotage? How can you break this pattern?",
"What is a situation that you found challenging, but that ultimately helped you grow? What did you learn from it?",
"What is something that you've always been curious about, but have never pursued? Why?",
"What is something that you're currently struggling with? How can you approach this challenge differently?",
"What is something that you've been avoiding because it makes you uncomfortable? How can you push past this discomfort?",
"What is a fear that you've overcome in the past? How did you do it?",
"What is something that you can do to be kinder to yourself? Why is self-compassion important?",
"What is something that you can do to take better care of your physical health? Why is this important?",
"What is something that you can do to improve your mental health? Why is this important?",
"What is a skill that you would like to learn? Why is it important to you?",
"In what ways have your priorities shifted over the past few years? Why do you think this is?",
"What is a habit that you would like to change in order to be more productive? Why?",
"What is something that you've been avoiding because it requires vulnerability? How can you embrace vulnerability in this situation?",
"In what ways do you tend to compare yourself to others? How can you break this pattern?",
"What is something that you can do to improve your relationships with others? Why is this important?",
"What is a value that you hold dear? How can you live in alignment with this value?",
"What is something that you've been putting off because you're afraid of failure? How can you reframe failure in this situation?",
"What is a limiting belief that someone else has placed on you? How can you break free from this belief?",
"What is something that you can do to be more present in your daily life? Why is this important?",
"What is a goal that you've been working towards for a long time? How can you break it down into smaller, actionable steps?",
"What is a situation that you found uncomfortable but ultimately led to personal growth? What did you learn from it?",
"What is something that you can do to be more authentic in your relationships with others? Why is this important?",
"What is a lesson that you've learned from a difficult experience? How has it helped you grow?",
"What is something that you can do to improve your emotional intelligence? Why is this important?",
"What is a place that you've visited that left a lasting impression on you? Why?",
"What is something that you've learned about yourself while travelling? How has it impacted you?",
"In what ways has travelling changed your perspective on the world?",
"What is a cultural experience that you've had while travelling that has challenged your beliefs or assumptions? How did you respond?",
"What is a place that you've always wanted to visit? Why does it hold such allure for you?",
"In what ways has travelling pushed you outside of your comfort zone? What have you learned from these experiences?",
"What is a trip that you've taken that didn't go as planned? What did you learn from this experience?",
"What is a place that you've visited that felt like home? What was it about this place that resonated with you?",
"What is a trip that you've taken that has brought you closer to someone else? How did it strengthen your relationship?",
"In what ways has travelling allowed you to connect with people from different backgrounds?",
"What is a place that you've visited that has inspired you creatively? How did it impact your art or writing?",
"What is a trip that you've taken that has taught you something about history? How has this knowledge impacted your understanding of the world?",
"What is a trip that you've taken that has made you appreciate your home country more? Why?",
"What is a place that you've visited that has a complicated history? How did this affect your experience there?",
"What is a trip that you've taken that has made you feel more connected to nature? How did this change your perspective?",
"What is a place that you've visited that has a rich culinary culture? What dishes did you try and enjoy?",
"What is a trip that you've taken that has helped you disconnect from technology and embrace mindfulness?",
"In what ways has travelling made you more resilient?",
"What is a place that you've visited that has a unique local art or music scene? How did this impact your experience there?",
"What is a trip that you've taken that has made you feel more grateful for your life and experiences?",
"What is a place that you've visited that has a rich spiritual or religious history? How did this affect your experience there?",
"What is a trip that you've taken that has made you feel more connected to your ancestry or cultural heritage?",
"In what ways has travelling made you more open-minded and accepting of different perspectives?",
"What is a place that you've visited that has a unique natural wonder or phenomenon? How did this impact your experience there?",
"What is a trip that you've taken that has taught you something new about yourself?",
"What is a place that you've visited that has a vibrant nightlife scene? How did this impact your experience there?",
"What is a trip that you've taken that has made you feel more empathetic towards others?",
"In what ways has travelling challenged your preconceived notions about a certain place or culture?",
"What is a place that you've visited that has a fascinating political or social history? How did this affect your experience there?",
"What is a trip that you've taken that has made you feel more adventurous and willing to take risks?",
"What does 'health and wellness' mean to you? How do you prioritize it in your life?",
"What is one healthy habit that you've developed that has positively impacted your overall well-being?",
"In what ways do you prioritize self-care in your daily routine?",
"What is a form of exercise that you enjoy and why?",
"In what ways does your diet impact your physical and mental health?",
"What is a wellness practice (meditation, yoga, mindfulness) that you've tried that has made a difference in your life?",
"What is a health or wellness goal that you've set for yourself? How do you plan to achieve it?",
"In what ways do your relationships impact your overall health and well-being?",
"What is a self-limiting belief that you have about your health? How can you challenge and overcome it?",
"What is a healthy habit that you struggle with maintaining? What steps can you take to make it easier?",
"What is a health or wellness accomplishment that you're proud of? How did you achieve it?",
"In what ways does your environment impact your health and well-being?",
"What is a wellness activity that you've always wanted to try? What's stopping you?",
"What is a habit that you know is detrimental to your health? What steps can you take to break it?",
"What is a healthy coping mechanism that you use to manage stress or difficult emotions?",
"In what ways do you prioritize sleep in your life? How does it impact your overall health and well-being?",
"What is a wellness practice that you've tried that hasn't worked for you? Why?",
"What is a way that you can incorporate more movement into your daily routine?",
"What is a healthy relationship with food? How can you cultivate it in your own life?",
"What is a health or wellness practice that you've always been curious about but hesitant to try?",
"In what ways does technology impact your health and well-being? How can you use it mindfully?",
"What is a habit that you want to break in order to improve your health? Why is it important to you?",
"What is a form of self-expression that brings you joy and contributes to your overall well-being?",
"What is a way that you can incorporate more nature into your daily routine? How does it impact your well-being?",
"What is a wellness practice that you can do with a partner or friend?",
"In what ways do you prioritize mental health in your life?",
"What is a way that you can incorporate more gratitude into your daily routine? How does it impact your well-being?",
"What is a wellness practice that you can do on-the-go or while traveling?",
"In what ways does your work or career impact your health and well-being? How can you find balance?",
"What is a way that you can incorporate more laughter into your daily routine? How does it impact your well-being?",
"What does a healthy relationship mean to you? How do you prioritize it in your life?",
"What is one thing that you appreciate about your partner/friend/family member?",
"In what ways do you communicate effectively in your relationships?",
"What is a boundary that you've set in a relationship? How has it impacted the dynamic?",
"In what ways do your past relationships impact your current ones?",
"What is a quality that you look for in a partner/friend/family member? Why is it important to you?",
"What is a relationship that you've had to let go of? How did it impact your personal growth?",
"In what ways do your own insecurities impact your relationships?",
"What is a way that you can show love and support to someone in your life?",
"What is a relationship that you need to repair? What steps can you take to make it better?",
"What is a healthy conflict resolution strategy that you use in your relationships?",
"In what ways does your cultural background impact your relationships?",
"What is a relationship dynamic that you struggle with? What steps can you take to improve it?",
"What is a relationship that you're grateful for? Why?",
"In what ways do you prioritize self-love in your relationships?",
"What is a way that you can be more present in your relationships?",
"What is a way that you can show gratitude towards someone in your life?",
"In what ways do your values align with your partner/friend/family member?",
"What is a way that you can prioritize quality time in your relationships?",
"What is a relationship that you've learned from? How has it impacted your personal growth?",
"In what ways do your own expectations impact your relationships?",
"What is a way that you can practice empathy in your relationships?",
"What is a healthy balance between giving and receiving in a relationship?",
"In what ways do your own biases impact your relationships?",
"What is a relationship that you need to set boundaries in? What steps can you take to make it healthier?",
"What is a way that you can practice forgiveness in your relationships?",
"What is a way that you can show appreciation towards someone in your life?",
"In what ways do your own fears impact your relationships?",
"What is a relationship that you need to let go of? How can you do it with compassion?",
"What is a way that you can practice open and honest communication in your relationships?",
"What does spirituality mean to you? How has it evolved over time?",
"What is your relationship with the universe, a higher power, or a divine source?",
"In what ways do you practice self-reflection and introspection in your spiritual journey?",
"What is a spiritual practice or ritual that you connect with on a deep level? How does it make you feel?",
"In what ways do you show gratitude for the blessings in your life through a spiritual lens?",
"What is a belief or concept in spirituality that you question or struggle with? Why?",
"In what ways does your spiritual journey impact your relationships and interactions with others?",
"What is a moment in your life where you felt a spiritual connection or awakening? How did it impact you?",
"What is a way that you can integrate spirituality into your daily routine or habits?",
"In what ways do you find comfort and solace in spirituality during difficult times?",
"What is a way that you can cultivate a sense of inner peace and stillness through spirituality?",
"What is a way that you can practice compassion and kindness towards yourself and others in a spiritual context?",
"In what ways do you practice forgiveness and release negative emotions through spirituality?",
"What is a way that you can connect with nature and the natural world in a spiritual context?",
"What is a way that you can cultivate a sense of community and belonging through spirituality?",
"What is a spiritual text or literature that has impacted your life? How?",
"In what ways do your cultural background and upbringing impact your spiritual beliefs and practices?",
"What is a way that you can tap into your intuition and inner guidance through spirituality?",
"What is a way that you can cultivate a sense of purpose and meaning through spirituality?",
"In what ways do you balance your spiritual beliefs with your practical everyday life?",
"What is a way that you can practice mindfulness and presence in a spiritual context?",
"What is a way that you can explore different spiritual practices and belief systems with an open mind?",
"In what ways do you find inspiration and motivation through spirituality?",
"What is a way that you can connect with your inner child and sense of wonder through spirituality?",
"What is a way that you can connect with and honor your ancestors or lineage through spirituality?",
"In what ways do you see spirituality as a journey or process rather than a destination?",
"What is a way that you can integrate creativity and self-expression into your spiritual practice?",
"What is a way that you can practice detachment and surrender through spirituality?",
"In what ways do you seek balance and harmony through spirituality?",
"What is a way that you can explore and honor the diversity of spiritual beliefs and practices around the world?",
"What is a traumatic experience that has impacted your life? How has it shaped you?",
"In what ways do you cope with and manage the aftermath of a traumatic event?",
"What is a way that you can seek support and healing from the effects of trauma?",
"What is a way that you can cultivate a sense of safety and security within yourself after experiencing trauma?",
"How has trauma impacted your relationships with others? In what ways do you navigate trust and vulnerability?",
"What is a way that you can practice self-compassion and forgiveness in the context of trauma?",
"In what ways do you cope with triggers and emotional responses related to trauma?",
"What is a way that you can recognize and honor the resilience and strength that comes from surviving trauma?",
"How has trauma impacted your perception of the world and others around you? In what ways do you challenge negative beliefs and thoughts?",
"What is a way that you can cultivate a sense of hope and optimism in the midst of trauma?",
"What is a way that you can find meaning and purpose in the aftermath of trauma?",
"In what ways do you engage in self-care and nurturing practices to support your healing from trauma?",
"What is a way that you can explore and express your emotions and experiences related to trauma through creative outlets?",
"What is a way that you can practice forgiveness and release towards those who may have caused or contributed to your trauma?",
"How has trauma impacted your mental and physical health? In what ways do you prioritize self-care in these areas?",
"What is a way that you can build a support network of individuals who can understand and empathize with your experiences of trauma?",
"In what ways do you navigate feelings of shame and guilt related to trauma?",
"What is a way that you can connect with and tap into your inner strength and resilience in the aftermath of trauma?",
"What is a way that you can work towards creating a sense of closure and acceptance around a traumatic experience?",
"In what ways do you challenge societal and cultural narratives surrounding trauma and healing?",
"What is a way that you can engage in activism or advocacy work related to trauma and its effects?",
"What is a way that you can approach healing from trauma as a process rather than a destination?",
"In what ways do you seek and accept help and support in the aftermath of trauma?",
"What is a way that you can find moments of joy and gratitude in the midst of healing from trauma?",
"How has trauma impacted your spirituality or beliefs about the universe and higher powers? In what ways do you find comfort and connection through these beliefs?",
"What is a way that you can build healthy and positive coping mechanisms to support your healing from trauma?",
"In what ways do you explore and accept the complexity of emotions and experiences related to trauma?",
"What is a way that you can practice boundary-setting and self-protection in the context of trauma?",
"What is a way that you can work towards forgiveness and compassion towards yourself in the aftermath of trauma?",
"In what ways do you approach healing from trauma as an opportunity for growth and transformation?",
"What did you do today that pushed you outside of your comfort zone?",
"Did you take time to truly connect with someone today, or did you just go through the motions?",
"What is one thing you did today that brought you closer to achieving your long-term goals?",
"Did you let fear or doubt hold you back from doing something today that you really wanted to do?",
"What is one thing you learned today that you didn't know before?",
"Did you treat yourself with kindness and compassion today, even in difficult moments?",
"Did you take time to appreciate the beauty of the world around you today?",
"What is one thing you did today that made someone else's day a little bit better?",
"What did you do today that challenged your assumptions or beliefs?",
"Did you take time to be present and fully engaged in each moment today, or did you rush through things?",
"What is one thing you did today that was difficult, but ultimately worth it?",
"Did you take time to express gratitude for the good things in your life today?",
"What is one thing you did today that you're proud of?",
"Did you take time to really listen to someone else's perspective today, even if you disagreed with it?",
"What is one thing you did today that challenged your creativity or imagination?",
"Did you take time to appreciate the simple pleasures of life today?",
"Did you take time to reflect on your values and priorities today?",
"What is one thing you did today that required you to be patient?",
"Did you take time to be fully present with your emotions today, even the difficult ones?",
"Did you take time to focus on your physical and mental health today?",
"What did you do today that made you feel truly alive?",
"What is one thing you did today that aligned with your purpose or passions?",
"What did you do today to contribute to a cause or community that you care about?",
"Did you take time to connect with nature today?",
"What did you do today that made you feel connected to a greater sense of meaning or purpose?",
"What is one thing you did today that helped you cultivate a sense of inner peace or contentment?",
"Did you take time to connect with your spiritual or philosophical beliefs today?",
"What did you do today that helped you develop a new skill or talent?",
"What is one thing you did today that you're grateful for?",
"What did you do today that helped you grow as a person?",
"What recurring dreams do you have, and what do you think they mean?",
"Do you believe that your dreams have any significance or meaning? Why or why not?",
"What is the most vivid dream you can remember, and how did it make you feel?",
"Have you ever had a dream that seemed to predict the future or offer guidance?",
"Do you have any recurring themes or symbols in your dreams, and what do they represent to you?",
"What fears or desires do your dreams reveal about your subconscious mind?",
"Have you ever had a lucid dream, where you were aware that you were dreaming? What did you do?",
"Do you believe that dreams can offer insights into your waking life and relationships? Why or why not?",
"What is the strangest or most surreal dream you can remember, and what do you think it means?",
"Have you ever had a nightmare that still haunts you? What was it about, and why do you think it affected you so deeply?",
"Do you believe that your dreams can be influenced by external factors, such as your environment or the media you consume?",
"What do you think your dreams say about your personality, values, or beliefs?",
"Have you ever had a dream that inspired you to take action in your waking life? What did you do, and why?",
"What is the most positive or uplifting dream you can remember, and how did it make you feel?",
"Do you believe that your dreams can reveal hidden truths about yourself or others? Why or why not?",
"What recurring emotions do you experience in your dreams, and how do they relate to your waking life?",
"Have you ever had a dream that challenged your assumptions or beliefs? What did you learn from it?",
"Do you believe that dreams can help you process and heal from past traumas or emotional experiences?",
"What is the most fantastical or imaginative dream you can remember, and what do you think inspired it?",
"Have you ever had a dream that made you question your sanity or reality? What was it about, and how did you cope?",
"Do you believe that your dreams can connect you to your spirituality or higher consciousness?",
"What is the most sensual or erotic dream you can remember, and how did it affect you?",
"Have you ever had a dream that helped you overcome a fear or phobia? What was it about, and how did it help?",
"Do you believe that dreams can offer glimpses into other dimensions or realities? Why or why not?",
"What recurring actions or events do you experience in your dreams, and how do they relate to your waking life?",
"Have you ever had a dream that helped you make a major life decision or change? What did you do, and why?",
"Do you believe that your dreams can offer clues about your past lives or future destiny? Why or why not?",
"What is the most bizarre or nonsensical dream you can remember, and what do you think it reflects about your mind?",
"Have you ever had a dream that made you feel like you had experienced something truly profound or mystical? What was it about, and how did it change you?",
"Do you believe that your dreams can reveal your deepest desires or fears, even if you're not consciously aware of them?",
]

function newPrompt() {
    var randomNumber = Math.floor(Math.random() * prompts.length);
    var quote = prompts[randomNumber];
    setCookie("quote", quote, 1); // set the quote cookie to expire in 1 day
    document.getElementById("quoteDisplay").innerHTML = "<q>" + quote + "</q>";
  }
  
  function setCookie(name, value, days) {
    var expires = "";
    if (days) {
      var date = new Date();
      date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
      expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + value + expires + "; path=/";
  }
  
  function getCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for (var i = 0; i < ca.length; i++) {
      var c = ca[i];
      while (c.charAt(0) == ' ') c = c.substring(1, c.length);
      if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
    }
    return null;
  }
  
  // check if a quote cookie exists and display it if it does
  var quote = getCookie("quote");
  if (quote) {
    document.getElementById("quoteDisplay").innerHTML = "<q>" + quote + "</q>";
  }

/* greeting */

// get the current hour
const hour = new Date().getHours();

// get the greeting based on the time of day
let greeting;
if (hour >= 5 && hour < 12) {
  greeting = "🔆 Good morning";
} else if (hour >= 12 && hour < 18) {
  greeting = "👋 Good afternoon";
} else if (hour >= 18 && hour < 22) {
  greeting = "👋 Good evening";
} else {
  greeting = "💤 It is getting late";
}

// update the greeting element
document.getElementById("greeting").textContent = greeting;





